### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [flbonanni/prj-rev-bwfs-dasmoto#2]
Overall excellent project.  When I look at this project I look for two items, did the learner use divs and was their css overly repetitive.  You were excellent on both.  I did mention font-weight:bold more to get you into the mindset to be as efficient as possible.  

Sometimes you have to repeat yourself especially as the projects become more complicate.  There also has been times in these later projects were I have suggested some ideas that remove as many as 50 lines of css.

As a challenge take a look at bootstrap getbootstrap.com and see if you can apply it to this site. It is a mobile friendly framework and some of the concepts will help prepare you for upcoming projects.

**Comment by flbonanni** [comment]
Thanks for the feedback! 

I followed your advice and downloaded bootstrap, I applied it to this site and uploaded the result in a new repo.
